In [10]:
import pandas as pd
import xlrd3 as xl
from geopy import distance

In [11]:
df = pd.read_excel("Hospital Lists.xlsx", engine="openpyxl")

In [12]:
df[df["District"] == "Narail"]

,Hospital Name,Speciality,District,Address,Full Address,Co-Ordinates,Contact Details,Unnamed: 7,Unnamed: 8
0,Maternity Hospital,Mothers and Child Care,Narail,"Chourasta, Narail","Chourasta, Narail, Bangladesh","23.172510917824084, 89.51107597729589",NaN,NaN,NaN
4,Doctor's Specialized Hospital limited.,General Hospital,Narail,"Lohagara, Narail","Lohagara - Jaipur Rd, Lohagara, Bangladesh","23.185010970556615, 89.65370669324409",8.801748e+12,NaN,NaN
10,50 Bed Hospital,General Hospital,Narail,"Digholia, Narail","Digholia, Narail, Bangladesh","22.8898099218669, 89.53532903864574",NaN,NaN,NaN
16,Janata Surgical Clinic,Surgical Clinic,Narail,Narail Sadar,Mohila College Road (North side of Civil Surge...,"23.17753096971635, 89.50104113742091",8.801716e+12,NaN,NaN

In [13]:
df = df.iloc[:,:-1]
df = df.iloc[:,:-1]

df

,Hospital Name,Speciality,District,Address,Full Address,Co-Ordinates,Contact Details
0,Maternity Hospital,Mothers and Child Care,Narail,"Chourasta, Narail","Chourasta, Narail, Bangladesh","23.172510917824084, 89.51107597729589",NaN
1,Gopalganj General Hospital,General Hospital,Gopalganj,"R850, গোপালগঞ্জ","R850, Gopalganj, Bangladesh","22.99881792342492, 89.81868872923526",NaN
2,Islami Bank Hospital,General Hospital,Khulna,"Shantidham More, Khulna","Khan Jahan Ali Rd, Shantidham More, Khulna 910...","22.811956945844756, 89.5615146033954",8.804173e+10
3,General Hospital,General Hospital,Khulna,"Hospital Rd, Khulna","Hospital Rd, Khulna 9100, Bangladesh","22.817546752517515, 89.56769159385654",NaN
4,Doctor's Specialized Hospital limited.,General Hospital,Narail,"Lohagara, Narail","Lohagara - Jaipur Rd, Lohagara, Bangladesh","23.185010970556615, 89.65370669324409",8.801748e+12
...,...,...,...,...,...,...,...
92,Nongor Diagonestic Center & Clinic,Diagonestic Center & Clinic,Pabna,NaN,"Pabna Sohor Rd, Pabna 6600","24.009318602150394, 89.23823745916017",8.807317e+10
93,Mymensingh Medical College & Hospital,Genaral Hospital,Mymensingh,NaN,"Char Para, Medical Rd, Mymensingh 2200","24.744351817283572, 90.40886755332832",NaN
94,Icon Diagnostic Center,Diagonestic Center,Mymensingh,NaN,"Dhaka-Mymensingh Rd, Chorpara, Mymensingh 2200","24.744585662694153, 90.40903923234262",NaN
95,CD Path & Hospital Pvt. Ltd.,Genaral Hospital,Cumilla,NaN,"Badurtala, Shishu Mangal Rd, Cumilla 3500","23.462525375765352, 91.17913007935894",8.801712e+12
96,Cumilla Diabetic Hospital,Diabetic Hospital,Cumilla,NaN,"Sulivan Road , Bagichagaon(near fire brigade p...","23.464832605545592, 91.17084302447361",NaN

In [14]:
import os
print(os.getcwd())

C:\Users\Hridoy\Documents\GitHub\Hospital-Recommendation-System

In [15]:
user_address = "23.13, 89.5"
user_address

'23.13, 89.5'

In [16]:
df["Co-Ordinates"][0]

'23.172510917824084, 89.51107597729589'

In [17]:
ls = []
for i in range(df["Co-Ordinates"].count()):
    ds = distance.distance(user_address, df["Co-Ordinates"][i]).km
    ls.append(ds)

ls

[4.842630553046063,
 35.74283906329068,
 35.78164090980967,
 35.29155500768171,
 16.877942182076474,
 15.516188529197786,
 15.140986494485762,
 16.66444500312346,
 16.029881029260462,
 33.98048678939684,
 26.845078800412637,
 29.736451285699005,
 15.654593323637163,
 34.083946043088645,
 35.55814789144226,
 30.157051622723554,
 5.264952213462622,
 29.860281794993632,
 30.53017722437823,
 30.0902081187194,
 29.844144830398445,
 29.674898333540472,
 29.637434644630314,
 29.45042471324409,
 29.642414989072766,
 27.233408846494743,
 30.16174035347347,
 29.994755596606723,
 29.691959454604838,
 30.01757508205677,
 29.92358258263549,
 30.48823052339652,
 29.800860722234752,
 62.9161616775392,
 67.32359965092563,
 63.356554752312526,
 63.09488815456162,
 63.35216861842417,
 63.36302177290623,
 63.21936098528414,
 63.146178111057075,
 65.25626432423161,
 63.32554050083888,
 63.35894035403389,
 63.65625282089905,
 57.07964053998135,
 57.36594132833929,
 55.66975974047812,
 55.95576210677953,
 53.11123727057457,
 57.46306018244147,
 57.37812699208923,
 55.50949973836571,
 55.6201814001552,
 93.63913906778419,
 93.61713029420648,
 254.33560262357497,
 251.4012521524393,
 250.50644265203877,
 254.34208924880213,
 254.03917822500784,
 253.19319752598307,
 252.42296953294445,
 251.0002394071673,
 250.5235944724691,
 253.08753415032473,
 322.5679805349241,
 316.13268071678385,
 316.4426533867671,
 315.9596040039993,
 309.5279109295116,
 309.71171132450337,
 309.69406981826995,
 311.05470789162484,
 311.1407896243371,
 311.1247128368103,
 120.41778375552467,
 121.45164280715497,
 119.92877679382657,
 119.19530196672012,
 116.30081127657334,
 113.60443668038734,
 116.25383354444811,
 115.41190563513155,
 115.77588833667895,
 115.83358067790964,
 113.9452471895634,
 116.70086861448009,
 117.19884954727142,
 119.73967959614491,
 166.13532201267782,
 101.70253875311943,
 100.98602481005419,
 201.3197281875058,
 201.35072610247065,
 175.672723036218,
 174.89647485203875]

In [18]:
df["Distance"] = ls
df

,Hospital Name,Speciality,District,Address,Full Address,Co-Ordinates,Contact Details,Distance
0,Maternity Hospital,Mothers and Child Care,Narail,"Chourasta, Narail","Chourasta, Narail, Bangladesh","23.172510917824084, 89.51107597729589",NaN,4.842631
1,Gopalganj General Hospital,General Hospital,Gopalganj,"R850, গোপালগঞ্জ","R850, Gopalganj, Bangladesh","22.99881792342492, 89.81868872923526",NaN,35.742839
2,Islami Bank Hospital,General Hospital,Khulna,"Shantidham More, Khulna","Khan Jahan Ali Rd, Shantidham More, Khulna 910...","22.811956945844756, 89.5615146033954",8.804173e+10,35.781641
3,General Hospital,General Hospital,Khulna,"Hospital Rd, Khulna","Hospital Rd, Khulna 9100, Bangladesh","22.817546752517515, 89.56769159385654",NaN,35.291555
4,Doctor's Specialized Hospital limited.,General Hospital,Narail,"Lohagara, Narail","Lohagara - Jaipur Rd, Lohagara, Bangladesh","23.185010970556615, 89.65370669324409",8.801748e+12,16.877942
...,...,...,...,...,...,...,...,...
92,Nongor Diagonestic Center & Clinic,Diagonestic Center & Clinic,Pabna,NaN,"Pabna Sohor Rd, Pabna 6600","24.009318602150394, 89.23823745916017",8.807317e+10,100.986025
93,Mymensingh Medical College & Hospital,Genaral Hospital,Mymensingh,NaN,"Char Para, Medical Rd, Mymensingh 2200","24.744351817283572, 90.40886755332832",NaN,201.319728
94,Icon Diagnostic Center,Diagonestic Center,Mymensingh,NaN,"Dhaka-Mymensingh Rd, Chorpara, Mymensingh 2200","24.744585662694153, 90.40903923234262",NaN,201.350726
95,CD Path & Hospital Pvt. Ltd.,Genaral Hospital,Cumilla,NaN,"Badurtala, Shishu Mangal Rd, Cumilla 3500","23.462525375765352, 91.17913007935894",8.801712e+12,175.672723
96,Cumilla Diabetic Hospital,Diabetic Hospital,Cumilla,NaN,"Sulivan Road , Bagichagaon(near fire brigade p...","23.464832605545592, 91.17084302447361",NaN,174.896475

In [19]:
a = "23.160815019824575, 89.20562386574234"
b = "23.174219949543314, 89.21414335931881"

d = distance.distance(a,b).km
print("% .2f" % d)

 1.72

In [20]:
df = df.sort_values(by="Distance").head(5)

In [21]:
import numpy as np
f = pd.DataFrame(np.random.randn(1000, 2) / [50, 50] + [37.76, -122.4], columns=['lat', 'lon'])
f.dtypes

lat    float64
lon    float64
dtype: object

In [22]:
map_data2 = pd.DataFrame({'lat': [23.172510917824084], 'lon': [89.51107597729589]})
map_data2

         lat        lon
0  23.172511  89.511076

In [23]:
df[["Lattitude", "Longitude"]] = df['Co-Ordinates'].str.split(',', expand=True)

In [24]:
df["Co-Ordinates"].count()

5

In [25]:
df

,Hospital Name,Speciality,District,Address,Full Address,Co-Ordinates,Contact Details,Distance,Lattitude,Longitude
0,Maternity Hospital,Mothers and Child Care,Narail,"Chourasta, Narail","Chourasta, Narail, Bangladesh","23.172510917824084, 89.51107597729589",NaN,4.842631,23.172510917824084,89.51107597729589
16,Janata Surgical Clinic,Surgical Clinic,Narail,Narail Sadar,Mohila College Road (North side of Civil Surge...,"23.17753096971635, 89.50104113742091",8.801716e+12,5.264952,23.17753096971635,89.50104113742091
6,L.B. Hospital,Diagnostic Center,Khulna,"Noapara Paurasava, Khulna","Noapara Paurasava, Bangladesh","23.028380799543278, 89.40114243434851",NaN,15.140986,23.028380799543278,89.40114243434851
5,Sarjikal Clinic,Diagnostic Center,Khulna,"Noapara Paurasava, Khulna","Hospital Rd, Noapara Paurasava, Bangladesh","23.028206943062095, 89.39594651259068",NaN,15.516189,23.028206943062095,89.39594651259068
12,Arogya Sadan (PVT) Hospital,General Hospital,Khulna,"Noapara Paurasava, Khulna","Noapara Paurasava, Bangladesh","23.02646447981799, 89.39598093864576",8.801711e+12,15.654593,23.02646447981799,89.39598093864576

In [36]:

map_data2 = df.iloc[:, -2:]
map_data2.dtypes

Lattitude    object
Longitude    object
dtype: object

In [40]:
import geocoder
ip = geocoder.ip("me")
ip

<[OK] Ipinfo - Geocode [Singapore, Singapore, SG]>